name: al_sirat
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/colors/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/inter/Inter-Bold.ttf
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
        - asset: assets/fonts/inter/Inter-Light.ttf
        - asset: assets/fonts/inter/Inter-Medium.ttf
        - asset: assets/fonts/inter/Inter-Regular.ttf
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
        - asset: assets/fonts/inter/Inter-Thin.ttf
    - family: tajawal
      fonts:
        - asset: assets/fonts/tajawal/Tajawal-Bold.ttf
        - asset: assets/fonts/tajawal/Tajawal-ExtraBold.ttf
        - asset: assets/fonts/tajawal/Tajawal-ExtraLight.ttf
        - asset: assets/fonts/tajawal/Tajawal-Light.ttf
        - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf


